### ISSUE TITLE
ระบบเพล์เช็ด 5 นาที ได้ 300

### ISSUE THREAD

**Issue by Admin-Heathcliff** [EGEStudio/SecretOne_LifeProject#21]

**Comment by EagleonePrimo** [comment]
น้อยไปป่าว คิดดูดีๆ

**Comment by Admin-Heathcliff** [comment]
ถ้ายังเพิ่มเป็น 500 ก็ได้ เพราะ อาวุท มันถูกน่ะพี่ สไน 5แสนเอง ปืนกลกระบอกไม่เกิน 8หมื่น

**Comment by EagleonePrimo** [comment]
1000 ขาดตัวไหนๆ ก็เซิฟ PVP

**Comment by EagleonePrimo** [comment]
paycheck_cop = 1000; //Payment for cops
paycheck_civ = 500; //Payment for civillians
