### ISSUE TITLE
ระบบกัน Alt+F4

### ISSUE THREAD

**Issue by Admin-Heathcliff** [EGEStudio/SecretOne_LifeProject#23]

**Comment by EagleonePrimo** [comment]
ถ่ายรูปมายืนยันหน่อย

**Comment by Admin-Heathcliff** [comment]
![2](https://cloud.githubusercontent.com/assets/23016790/22541885/ae1f8e08-e95b-11e6-8ca8-e97e482eb51e.jpg)
