### ISSUE TITLE
ดูจุดตัวเองในแผนที่ได้

### ISSUE THREAD

**Issue by Admin-Heathcliff** [EGEStudio/SecretOne_LifeProject#29]
- รายการรอการตรวจสอบ
- [x] ประชาชน
- [x] หมอ
- [x] ตำรวจ

**Comment by EagleonePrimo** [comment]
- รายการรอการตรวจสอบ
-[ ] ประชาชน
-[ ] หมอ
-[ ] ตำรวจ

**Comment by EagleonePrimo** [comment]
ทดสอบทุกหนวยงานยัง หมอ ตำรวจ ประชาชน

**Comment by Admin-Heathcliff** [comment]
ของหมอค้าง ตัวอยู่สนามบิน จุดอยู่ที่โรงบาล ไม่ขยับตามตัว
![4](https://cloud.githubusercontent.com/assets/23016790/22577708/f4d28a7c-e9f5-11e6-8bba-72df8b2226ad.jpg)

![3](https://cloud.githubusercontent.com/assets/23016790/22577691/deff2426-e9f5-11e6-85d6-8e746e153a2a.jpg)

**Comment by EagleonePrimo** [comment]
ไอ้ตัวที่เอ๋งถ่ามมามันคือ ร้านขาย ฮอ

**Comment by EagleonePrimo** [comment]
ขอ ไฟล์ log .prt หน่อย

**Comment by EagleonePrimo** [comment]
ไหนบอกว่าของหมอมันบัค

**Comment by Admin-Heathcliff** [comment]
บ้างที่ มันก็ตาม บ้างทีก็ไม่ตาม แต่ หมอด้วยกันมองรู้ว่าจูดเพื่อน อยู่ตรงไหนบ้าง

**Comment by EagleonePrimo** [comment]
` 8:47:43 Error in expression <_medics = [];
waitUntil {!visibleMap};
{deleteMarkerLocal _x;} forEach _markers;>
 8:47:43   Error position: <deleteMarkerLocal _x;} forEach _markers;>
 8:47:43   Error deletemarkerlocal: Type Array, expected String
 8:47:43 File mpmissions\__CUR_MP.Altis\core\medical\fn_medicMarkers.sqf, line 70
 8:47:55 Strange convex component317 in a3\rocks_f\blunt\bluntrock_wallv.p3d:geometry
 8:47:55 Strange convex component318 in a3\rocks_f\blunt\bluntrock_wallv.p3d:geometry
 8:47:55 Strange convex component319 in a3\rocks_f\blunt\bluntrock_wallv.p3d:geometry
 8:47:55 Strange convex component317 in a3\rocks_f\blunt\bluntrock_wallv.p3d:geometryView
 8:47:55 Strange convex component318 in a3\rocks_f\blunt\bluntrock_wallv.p3d:geometryView
 8:47:55 Strange convex component319 in a3\rocks_f\blunt\bluntrock_wallv.p3d:geometryView
 8:47:56 "2h 30min | SecretOne(76561199197498415) | Teleport to [18160.1,19218.3,0](GPS: 181192)"
 8:47:56 "2h 30min | SecretOne(76561199197498415) | Teleport to [18160.1,19218.3,0](GPS: 181192)"
 8:47:57 Error in expression <_medics = [];
waitUntil {!visibleMap};
{deleteMarkerLocal _x;} forEach _markers;>
 8:47:57   Error position: <deleteMarkerLocal _x;} forEach _markers;>
 8:47:57   Error deletemarkerlocal: Type Array, expected String
 8:47:57 File mpmissions\__CUR_MP.Altis\core\medical\fn_medicMarkers.sqf, line 70
 8:48:04 "2h 30min | SecretOne(76561199197498415) | Teleport to [18137.1,19207.3,0](GPS: 181192)"
 8:48:04 "2h 30min | SecretOne(76561199197498415) | Teleport to [18137.1,19207.3,0](GPS: 181192)"
 8:48:06 Error in expression <_medics = [];
waitUntil {!visibleMap};
{deleteMarkerLocal _x;} forEach _markers;>
 8:48:06   Error position: <deleteMarkerLocal _x;} forEach _markers;>
 8:48:06   Error deletemarkerlocal: Type Array, expected String
 8:48:06 File mpmissions\__CUR_MP.Altis\core\medical\fn_medicMarkers.sqf, line 70
 8:48:13 Error in expression <_medics = [];
waitUntil {!visibleMap};
{deleteMarkerLocal _x;} forEach _markers;>
 8:48:13   Error position: <deleteMarkerLocal _x;} forEach _markers;>
 8:48:13   Error deletemarkerlocal: Type Array, expected String
 8:48:13 File mpmissions\__CUR_MP.Altis\core\medical\fn_medicMarkers.sqf, line 70`

**Comment by EagleonePrimo** [comment]
แก้อันล่าสุดแล้ว f953ae04e761a1c9b4f89a4cf46f701dadbc1693
