### ISSUE TITLE
ระบบ VIP และมี icon มงกุฎเหนือชื่อตัวละคร

### ISSUE THREAD

**Issue by Admin-Heathcliff** [EGEStudio/SecretOne_LifeProject#35]
VIP มี 3 ระดับ มีดังนี้
- Lv.1 Bronze Class
- [ ] เงินPaycheak ในเกม +1500 ทุก 5 นาที
- [ ] ซื้อชุดได้ถูกลง 25%
- [ ] icon มงกุฎสีทองแดงเหนือชื่อตัวละคร
- Lv.2  Silver Class
- [ ] เงิน Paycheak ในเกม +2000 ทุก 5 นาที
- [ ] ซื้อชุดได้ถูกลง 25%
- [ ] ซื้อรถได้ถูกลง 30%
- [ ] icon มงกุฎสีเงินเหนือชื่อตัวละคร
- Lv.3  Gold Class
- [ ] เงิน Paycheak ในเกม +2500 ทุก 5 นาที
- [ ] ซื้อชุดได้ถูกลง 25%
- [ ] ซื้อรถได้ถูกลง 30%
- [ ] ซื้ออาวุทได้ถูกลง 25%
- [ ] มีจุดเกิดที่ Rebel
- [ ] icon มงกุฎสีทองเหนือชื่อตัวละคร

**Comment by EagleonePrimo** [comment]
มึงไป กอป เข้ามาใช่ไหม

**Comment by Admin-Heathcliff** [comment]
ช่ายเลย ผมขอ ระบบ VIP ก่อนได้ไหม จะได้ ปล่อยให้ โดเนท
