### ISSUE TITLE
แจ้งบัค 31/1/60

### ISSUE THREAD

**Issue by Admin-Heathcliff** [EGEStudio/SecretOne_LifeProject#7]
![default](https://cloud.githubusercontent.com/assets/23016790/22463304/94a4ab4e-e7e3-11e6-9a87-a84366ed09b5.jpg)
1. Hunting Grounds    มีสัตว์น้อยเกินไป       วิ่งมเกือบ20นาที  เจอ2ตัว-*-
2. เพิ่มวงแดงในธนาคาร
3.อินฟิก แพงอีกนิด จะดีมาก สัก 250k เพราะทำงานมันก้ 200-300k อ้ะน้ะ   
4. ซื้อของบัค  เวลากดBuy มันทับ
5.ดิสแล้วปืนหาย

**Comment by EagleonePrimo** [comment]
เอาไปแยก ข้อนะ
